/**
 * Russian
 *
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 *
 */
//Г     Д    Ж    И   Л    П    Ы     Я
//\x00 \x01 \x02 \x03 \x04 \x05 \x06 \x07   

#ifndef LANGUAGE_RU_H
#define LANGUAGE_RU_H

#define LANGUAGE_RU

#define WELCOME_MSG                         MACHINE_NAME " ГOTOB"
#define MSG_SD_INSERTED                     "KAPTA BCTAB" "\x04" "EHA"
#define MSG_SD_REMOVED                      "HET KAPT\x06"
#define MSG_MAIN                            "OCHOBHO\x03" " PA3\x01" "E\x04"
#define MSG_AUTOSTART                       "ABTOCTAPT"
#define MSG_DISABLE_STEPPERS                "OTK\x04. MOTOP\x06"
#define MSG_AUTO_HOME                       "\x05" "APKOBKA"
#define MSG_SET_HOME_OFFSETS                "3A\x01" "ATb C\x01" "B\x03Г HY\x04\x07"
#define MSG_SET_ORIGIN                      "YCTAHOB\x03Tb HO\x04b"
#define MSG_PREHEAT_PLA                     "\x05PE\x01HAГPEB PLA"
#define MSG_PREHEAT_PLA0                    "\x05PE\x01HAГPEB PLA 1"
#define MSG_PREHEAT_PLA1                    "\x05PE\x01HAГPEB PLA 2"
#define MSG_PREHEAT_PLA2                    "\x05PE\x01HAГPEB PLA 3"
#define MSG_PREHEAT_PLA012                  "HAГPETb BCE"
#define MSG_PREHEAT_PLA_BEDONLY             "HAГPETb CTO\x04"
#define MSG_PREHEAT_PLA_SETTINGS            "HACTPO\x03K\x03 PLA"
#define MSG_PREHEAT_ABS                     "\x05PE\x01HAГPEB ABS"
#define MSG_PREHEAT_ABS0                    "\x05PE\x01HAГPEB ABS 1"
#define MSG_PREHEAT_ABS1                    "\x05PE\x01HAГPEB ABS 2"
#define MSG_PREHEAT_ABS2                    "\x05PE\x01HAГPEB ABS 3"
#define MSG_PREHEAT_ABS012                  "HAГPETb BCE"
#define MSG_PREHEAT_ABS_BEDONLY             "HAГPETb CTO\x04"
#define MSG_PREHEAT_ABS_SETTINGS            "HACTPO\x03K\x03 ABS"
#define MSG_COOLDOWN                        "OTK\x04. HAГPEB"
#define MSG_SWITCH_PS_ON                    "BK\x04 B\x05"
#define MSG_SWITCH_PS_OFF                   "OTK\x04. B\x05"
#define MSG_EXTRUDE                         "ДABИTb MATEPИA" "\x04"
#define MSG_RECTRACT                        "OTKAT MATEP\x03" "A\x04" "A"
#define MSG_LOAD                            "3AГPY3\x03Tb MATEP" "\x03" "A" "\x04"
#define MSG_MOVE_AXIS                       "\x01" "B\x03" "\x02" "EH\x03" "E \x05O OC\x07M"
#define MSG_MOVE_X                          "\x05O OC\x03 X"
#define MSG_MOVE_Y                          "\x05O OC\x03 Y"
#define MSG_MOVE_Z                          "\x05O OC\x03 Z"
#define MSG_MOVE_E                          "\x05O OC\x03 E" " (\x05" "PYTOK)"
#define MSG_MOVE_E1                         "\x05O OC\x03 E1" " (\x05" "PYTOK)"
#define MSG_MOVE_E2                         "\x05O OC\x03 E2" " (\x05" "PYTOK)"
#define MSG_MOVE_01MM                       "HA 0.1mm"
#define MSG_MOVE_1MM                        "HA 1mm"
#define MSG_MOVE_10MM                       "HA 10mm"
#define MSG_SPEED                           "CKOPOCTb"
#define MSG_NOZZLE                          "t CO\x05\x04O"
#define MSG_NOZZLE1                         "t CO\x05\x04O1"
#define MSG_NOZZLE2                         "t CO\x05\x04O2"
#define MSG_BED                             "t CTO\x04"
#define MSG_FAN_SPEED                       "BEHT. CO\x05" "\x04" "A"
#define MSG_FLOW                            "\x05OTOK"
#define MSG_FLOW0                           " \x05OTOK0"
#define MSG_FLOW1                           " \x05OTOK1"
#define MSG_FLOW2                           " \x05OTOK2"
#define MSG_CONTROL                         "2.\x05" "APAMETP\x06"
#define MSG_MIN                             " *t M\x03H"
#define MSG_MAX                             " *t MAKC"
#define MSG_FACTOR                          " *\x05" "O\x05" "PABKA"
#define MSG_AUTOTEMP                        "ABTOTEM\x05"
#define MSG_ON                              "BK\x04"
#define MSG_OFF                             "OTK\x04"
#define MSG_PID_P                           "PID-P"
#define MSG_PID_I                           "PID-I"
#define MSG_PID_D                           "PID-D"
#define MSG_PID_C                           "PID-C"
#define MSG_ACC                             "Acc"
#define MSG_VXY_JERK                        "Vxy-jerk"
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax"
#define MSG_X                               "x"
#define MSG_Y                               "y"
#define MSG_Z                               "z"
#define MSG_E                               "e"
#define MSG_VMIN                            "Vmin"
#define MSG_VTRAV_MIN                       "VTrav min"
#define MSG_AMAX                            "Amax "
#define MSG_A_RETRACT                       "A-retract"
#define MSG_XSTEPS                          "Xsteps/mm"
#define MSG_YSTEPS                          "Ysteps/mm"
#define MSG_ZSTEPS                          "Zsteps/mm"
#define MSG_ESTEPS                          "Esteps/mm"
#define MSG_TEMPERATURE                     "TEM\x05" "EPATYPA"
#define MSG_MOTION                          "CKOPOCTb"
#define MSG_VOLUMETRIC                      "MATEP\x03" "A\x04"
#define MSG_VOLUMETRIC_ENABLED		        " E В mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "H\x03Tb " "\x01" "\x03" "AM 1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Fil. Dia. 2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Fil. Dia. 3"
#define MSG_CONTRAST                        "LCD KOHTPACT"
#define MSG_STORE_EPROM                     "COXPAH\x03" "Tb B EPROM"
#define MSG_LOAD_EPROM                      "3AГPY3KA " "\x03" "3 EPROM"
#define MSG_RESTORE_FAILSAFE                "\x03" "CXO\x01" "H\x06" "E \x05" "APAMETP\x06"
#define MSG_REFRESH                         "O6HOB\x03" "Tb"
#define MSG_WATCH                           "KOHTPO\x04" "b"
#define MSG_PREPARE                         "1.\x05O\x01ГOTOBKA"
#define MSG_TUNE                            "\x05" "O\x01" "CTPO\x03KA"
#define MSG_PAUSE_PRINT                     "\x05" "AY3A 3A\x01" "AH\x03" "E"
#define MSG_RESUME_PRINT                    "\x05" "PO\x01" "O\x04" "\x02" "\x03" "Tb 3A\x01" "AH\x03" "E"
#define MSG_STOP_PRINT                      "CTO\x05" " 3A\x01" "AH\x03" "E"
#define MSG_CARD_MENU                       "3.SD KAPTA"
#define MSG_NO_CARD                         "3.HET SD KAPT\x06"
#define MSG_DWELL                           "COH..."
#define MSG_USERWAIT                        "\x02\x01Y" "\x05" "O\x01" "TBEP\x02" "\x01" "EH\x03" "\x07"
#define MSG_RESUMING                        "\x05" "PO\x01" "O\x04" "\x02" "\x03" "Tb 3A\x01" "AH\x03" "E"
#define MSG_PRINT_ABORTED                   "3A\x01" "AH\x03" "E \x05" "PEPBAHO"
#define MSG_NO_MOVE                         "HET \x01" "B\x03" "\x02" "EH\x03" "\x07."
#define MSG_KILLED                          "OTMEHEHO"
#define MSG_STOPPED                         "OCTAHOB\x04EHO."
#define MSG_CONTROL_RETRACT                 "OTKAT mm:"
#define MSG_CONTROL_RETRACT_SWAP            "CBO\x05 OTKAT mm:"
#define MSG_CONTROL_RETRACTF                "OTKAT  V:"
#define MSG_CONTROL_RETRACT_ZLIFT           "\x05O\x01H\x07Tb Z mm:"
#define MSG_CONTROL_RETRACT_RECOVER         "OTKAT +mm:"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "CBO\x05 OTKAT +mm:"
#define MSG_CONTROL_RETRACT_RECOVERF        "OTKAT  V:"
#define MSG_AUTORETRACT                     "ABTOOTKAT:"
// TODO_MY
#define MSG_FILAMENTCHANGE                  "CMEH\x03" "Tb MATEP\x03" "A\x04"
#define MSG_INIT_SDCARD                     "\x05" "O\x01" "ГOTOB\x03" "Tb SD-KAPTY"
#define MSG_CNG_SDCARD                      "CMEH\x03" "Tb SD-KAPTY"
#define MSG_ZPROBE_OUT                      "Z probe out. bed"
#define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define MSG_ZPROBE_ZOFFSET                  "offset Z probe"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Endstop abort"

#define MSG_BACK                            "HA3A" "\x01"

#define MSG_HEATING                         "HAГPEB CO\x05" "\x04" "A..."
#define MSG_HEATING_COMPLETE                "HAГPEB B\x06" "\x05" "O\x04" "HEH"
#define MSG_BED_HEATING                     "HAГPEB CTO\x04" "A..."
#define MSG_BED_DONE                        "CTO\x04" " HAГPET"

#ifdef DELTA_CALIBRATION_MENU
    #define MSG_DELTA_CALIBRATE             "Delta Calibration"
    #define MSG_DELTA_CALIBRATE_X           "Calibrate X"
    #define MSG_DELTA_CALIBRATE_Y           "Calibrate Y"
    #define MSG_DELTA_CALIBRATE_Z           "Calibrate Z"
    #define MSG_DELTA_CALIBRATE_CENTER      "Calibrate Center"
#endif // DELTA_CALIBRATION_MENU

#endif // LANGUAGE_RU_H

